[package]
name = "speedtest"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
num-format = "0.4"
chrono = "0.4"
